server:
  port: 8027

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: api-boss

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:13306/service_driver_user?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: password