server:
  port: 8027
  servlet:
    context-path: /api-boss

spring:
  application:
    name: api-boss
#  profiles:
#    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    com.alibaba.nacos: DEBUG

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:13306/service_driver_user?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    passwo rd: password