spring:
  application:
    name: service-verificationcode
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        cluster-name: bj
server:
  port: 8022