spring:
  application:
    name: service-verificationcode
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

    sentinel:
      transport:
        dashboard: localhost:8070
#        port: 8719
      eager: true
      web-context-unify: false
server:
  port: 8022

# 暴露Actuator端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'