server:
  port: 10000


spring:
  data:
    redis:
      host: localhost
      port: 5001
      password: mypassword
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

    gateway:
      routes:
        - id: order
#          uri: http://localhost:8029
#          predicates:
#            - Path= /order/**
          uri: lb://service-order
          predicates:
            - Path= /service-order/**
            - After=2025-06-29T17:31:00.789+08:00[Asia/Shanghai]
          filters:
            - StripPrefix=1

        - id: api-passenger
          uri: lb://api-passenger
          predicates:
            - Path=/api-passenger/**
          filters:
#            - StripPrefix=1
        - id: api-driver
          uri: lb://api-driver
          predicates:
            - Path=/api-driver/**
          filters:
#            - StripPrefix=1
        - id: api-boss
          uri: lb://api-boss
          predicates:
            - Path=/api-boss/**
          filters:
#            - StripPrefix=1

  application:
    name: cloud-gateway

logging:
  level:
    com.springframework: info