server:
  port: 8030

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    loadbalancer:
      enabled: true
  application:
    name: service-pay
  data:
    redis:
      host: localhost
      port: 5001
      password: mypassword

alipay:
  appId: 9021000149686201
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCBpb11wyMVx1sHTHACyWO6cyhwEiAtWqTr2XIZUDuQ+CgSKsxcox7X/CexUJ2aCzJ3E/U/39kDNos6AxnIjDUCQXjwCNe8zQ3u2xOkpyU7Dt+9qAh6qtMcRYHGwUpOmmxxrsiYGc33Tl31fHPV1EFoLZB/fqk08n7Hm6WJh2Tc1vY23sq3kgsSDEbHVMSAeSND+p8kgLPCA0YckI1ZZQz6DYTZyWmbDSOt6JxddHLGtyeTtmGx+2b5yv9Ob/k9DOGxW1UqtsgDXx2I2A18f8xd+GriHOhIneNkdpl8S9DT26j9K0/F12NiPJCaQTrC5kVaqzhd2LQT0wZJp9Ev0PuZAgMBAAECggEANGzV6PnIhTUA/TmOjcHr/ug0MOVTd6OQzwI13kCQZbXDVl1SGB+qCEKhtlTX9gOTG43JfVPCSEdVE1dPpMX1ZX0eL0oUGvd8K9sQ3WLtbi08kk+RZjEPfv4oVTuyFYjiUzIPUVoV7GwXGH6DxLK45CyQos2QFKX+WC77SFqkkZwTlavPrUHUITyrQNHHp34CA/xMmylGsxOKC1PzJXY2Zt8jDaNf3RZ+VQxE34Qe72G0QTwosuL5dvr+asdJfHz9gLntbJ5/zdJqQtJ+ZrZJTujXhpUEkXt/uflrIH3VhiZy+w+uHi7NApXHh21CcQqckxkxTTa0vaPanYrMp5VQgQKBgQDAK64uChHYAsePf92ioUcd9WOUxc46WQskk9v86+qtkyVvGPc5XG0Tsgm7pxMM2H0Fj749CisULV4RGATlCmrp2aYo8Zw4/9Q03V+coZDoZPHGDpUI/pJ0HZNbFY8JleVqrc7D48/YejzW9WWKJbyjLwoplJk1fM2B4WOapyD7yQKBgQCstbHobk9L9mfOV7Gg90zmTt36WWKitn0SKBOG9PTLmlw6YGGJx2DrqDCVOy09STpW2MGOGpF2W4PNNN2p1WO/ghY8L491xOUzQKISxjwaUW7VIcWH14s8EIn+cXhWQjji9cItfJI10S8bPytUDHvuS0wB0//iPUFFhsTOIm1JUQKBgCOqN6pdvhAL/AN65KRhMDS0LSYYS/zyN6ozMtnO4wAR1hm3VXK0352PJlVIXbW9m/5jPhhQAcy92r5racUkWNFLzpW8uZSujjC9gRgtuBoZWfG7FRfVP1MDhiyaZLCPvEM/PKeIaTOxBAeVBaJM/KSAf29WH9UYc3+OWBEEwY9ZAoGBAKjev6XUthRASh+n/za0l6xZURKIc7lFVeV66hz7RqANvkAWHUjqegnx2g8QXZufDjv8lMStla10rdrn5hU5YN7QA421s0Aj1TfX6qEQ05OoLAaZjtrUFoAUa9kuectd1OGWCtcPBqc4cibiDSuRSVwmo5rl/zznR/sDW0tyvgkBAoGBAJwQDGrdM9ylQScMSebtLQC4EIAQg96V449gYAwpTNsSJqwEE8ldUpoRRYL2FvKbc2jPIv/GiAnE48yleSWHnlb/+JCxk2L97ClVTiAPKGx8jaSH3AxQc/q7D8v+pTCcE4cUn5H8XtfZjOFLs7xLGgITMgmfdYDldGvFjHS65XiL
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArhQjNLOmvoyVs66ViIxTFcRsR/zfSMNBSTDQfyIi1cnDgmUZ9Q2FUQZYeyPePdFeUKMYWQCk/Hngmil14QgXs6PMgLtoGsecGuO9eQ4zIuzKy7Ho3NI6h3zutDUMM3iu6Jox8rumLCOvQ+Y2BJyQRuSqGmx6msQwm/Z3fU5me0rz/0R+Lu9tTgIoL/klfknVtBsx5eEsbx8h8jEawepqpHCo2TnpGnaLLEnrtGh6aOLgmm1IpkVS5Cg7KyyYIrUgRLzuI7IAVqOD2Vv8yhzjU56sMdj0uAz8QwI2hSiYZDe7wnOTAPVMhs97GPSQuDVXgW+XCYg5ZTl8KXonIFBvpwIDAQAB
  notifyUrl: https://1jn1018sb0765.vicp.fun/alipay/notify