server:
  port: 8028
  servlet:
    context-path: /api-driver

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: api-driver

  data:
    redis:
      host: localhost
      port: 5001
      password: mypassword

seata:
  service:
    vgroup-mapping.my_tx: seata-tc
    grouplist.seata-tc: 127.0.0.1:8091
  tx-service-group: my_tx

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:13306/service_driver_user?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: password