server:
  port: 8021


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: api-passenger

#spring:
#  config:
#    import[0]: nacos:springclouddemo2023x.properties?group=DEFAULT_GROUP
#  cloud:
#    nacos:
#      config:
#        server-addr: 127.0.0.1:8848